import turtle as t
import random
import time

def title():
    # begin
    t.shape("turtle")
    t.pensize(5)
    t.pencolor("red")
    # character W
    t.speed(0)
    t.penup()
    t.goto(-200, 300)
    t.pendown()
    t.goto(-175, 200)
    t.goto(-150, 300)
    t.goto(-125, 200)
    t.goto(-100, 300)
    # character I
    t.penup()
    t.goto(-90, 300)
    t.pendown()
    t.goto(-90, 200)
    # character N
    t.penup()
    t.goto(-80, 200)
    t.pendown()
    t.goto(-80, 300)
    t.goto(-10, 200)
    t.goto(-10, 300)
    # character N
    t.penup()
    t.goto(0, 200)
    t.pendown()
    t.goto(0, 300)
    t.goto(70, 200)
    t.goto(70, 300)
    # character E
    t.penup()
    t.goto(80, 300)
    t.pendown()
    t.goto(140, 300)
    t.goto(80, 300)
    t.goto(80, 250)
    t.goto(130, 250)
    t.goto(80, 250)
    t.goto(80, 200)
    t.goto(140, 200)
    # character R
    t.penup()
    t.goto(150, 250)
    t.pendown()
    t.goto(200, 250)
    t.goto(200, 300)
    t.goto(150, 300)
    t.goto(150, 200)
    t.goto(150, 250)
    t.goto(200, 200)
    t.penup()

def number_processing(x):
    if x < 10:
        s = "00" + str(x)
    elif x < 100:
        s = "0" + str(x)
    else:
        s = str(x)
    return s

def write_numbers(str_x):
    
    def write_a_num(s):
        if s is "1":
            t.penup()
            t.forward(100)
            t.pendown()
            t.right(90)
            t.forward(200)
            t.forward(-200)
            t.left(90)
            t.penup()
            t.forward(30)
        if s is "2":
            t.pendown()
            t.forward(100)
            t.right(90)
            t.forward(100)
            t.right(90)
            t.forward(100)
            t.left(90)
            t.forward(100)
            t.left(90)
            t.forward(100)
            t.penup()
            t.left(90)
            t.forward(200)
            t.right(90)
            t.forward(30)
        if s is "3":
            t.pendown()
            t.forward(100)
            t.right(90)
            t.forward(100)
            t.right(90)
            t.forward(100)
            t.forward(-100)
            t.left(90)
            t.forward(100)
            t.right(90)
            t.forward(100)
            t.penup()
            t.right(90)
            t.forward(200)
            t.right(90)
            t.forward(100)
            t.forward(30)
        if s is "4":
            t.pendown()
            t.right(90)
            t.forward(100)
            t.left(90)
            t.forward(100)
            t.right(90)
            t.forward(100)
            t.forward(-200)
            t.left(90)
            t.penup()
            t.forward(30)
        if s is "5":
            t.pendown()
            t.forward(100)
            t.forward(-100)
            t.right(90)
            t.forward(100)
            t.left(90)
            t.forward(100)
            t.right(90)
            t.forward(100)
            t.right(90)
            t.forward(100)
            t.penup()
            t.forward(-100)
            t.right(90)
            t.forward(200)
            t.right(90)
            t.forward(30)
        if s is "6":
            t.pendown()
            t.forward(100)
            t.forward(-100)
            t.right(90)
            t.forward(200)
            t.left(90)
            t.forward(100)
            t.left(90)
            t.forward(100)
            t.left(90)
            t.forward(100)
            t.penup()
            t.right(90)
            t.forward(100)
            t.right(90)
            t.forward(100)
            t.forward(30)
        if s is "7":
            t.pendown()
            t.forward(100)
            t.right(90)
            t.forward(200)
            t.forward(-200)
            t.left(90)
            t.penup()
            t.forward(30)
        if s is "8":
            t.pendown()
            t.right(90)
            for i in range(4):
                t.forward(100)
                t.left(90)
            t.forward(200)
            t.left(90)
            t.forward(100)
            t.left(90)
            t.forward(200)
            t.penup()
            t.right(90)
            t.forward(30)
        if s is "9":
            t.pendown()
            for i in range(4):
                t.forward(100)
                t.right(90)
            t.forward(100)
            t.right(90)
            t.forward(200)
            t.right(90)
            t.forward(100)
            t.forward(-100)
            t.left(90)
            t.forward(-200)
            t.penup()
            t.left(90)
            t.forward(30)
        if s is "0":
            t.pendown()
            t.forward(100)
            t.right(90)
            t.forward(200)
            t.right(90)
            t.forward(100)
            t.right(90)
            t.forward(200)
            t.right(90)
            t.penup()
            t.forward(100)
            t.forward(30)

    t.penup()
    t.goto(-180, 100)
    t.pencolor("green")
    for c in str_x:
        write_a_num(c)
        
        
def main():
    # t.speed(0)
    winner_list = []
    t.clear()
    title()
    num = range(1,47)
    random.shuffle(num)
    winner_list.extend(num[:1])
    for a in winner_list:
        a = number_processing(a)
        write_numbers(a)
        
    t.done()
    print(winner_list)
    
    
if __name__ == "__main__":
    main()

